require:
  - rubocop-rspec
  - rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "db/**/*"
    - "config/**/*"
    - "script/**/*"
    - "spec/rails_helper.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  IgnoredMethods: ["describe", "context", "feature", "scenario", "let"]

Layout/LineLength:
  Max: 80
